server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    enabled-protocols: ${SSL_PROTOCOLS}
    key-store: conf/key/${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}

aleta:
  localPath: ${ALETA_LOCAL_PATH}

http:
  schedulerUrl: ${HTTP_SCHEDULER_URL}
  riskEngineUrl: ${RISK_ENGINE_URL}
  cryptoEngineUrl: ${CRYPTO_ENGINE_URL}

notification:
  otc-agreed-recipient: ${NOTIFICATION_OTC_AGREED_RECIPIENT}
  otc-high-risk-recipient: ${NOTIFICATION_OTC_HIGH_RISK_RECIPIENT}
  finance-recipient: ${NOTIFICATION_FINANCE_RECIPIENT}
  portal-url-prefix: ${PORTAL_URL_PREFIX}

etherscan:
  api-url-prefix: ${ETHERSCAN_API_URL_PREFIX}
  api-key: ${ETHERSCAN_API_KEY}
  max-end-block: ${ETHERSCAN_MAX_END_BLOCK}

silvergate:
  dev-mode: ${SILVERGATE_DEV_MODE}
  api-url-prefix: ${SILVERGATE_API_URL_PREFIX}
  sen-account-info: ${SILVERGATE_SEN_ACCOUNT_INFO}
  trading-account-info: ${SILVERGATE_TRADING_ACCOUNT_INFO}
  web-hook-url: ${SILVERGATE_WEB_HOOK_URL}
  web-hook-emails: ${SILVERGATE_WEB_HOOK_EMAILS}
  web-hook-sms: ${SILVERGATE_WEB_HOOK_SMS}
  certificate-path: ${SILVERGATE_CERTIFICATE_PATH}
  certificate-password: ${SILVERGATE_CERTIFICATE_PASSWORD}