server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    enabled-protocols: ${SSL_PROTOCOLS}
    key-store: conf/key/${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}

aleta:
  localPath: ${ALETA_LOCAL_PATH}

http:
  schedulerUrl: ${HTTP_SCHEDULER_URL}

notification:
  otc-agreed-recipient: ${NOTIFICATION_OTC_AGREED_RECIPIENT}
  otc-high-risk-recipient: ${NOTIFICATION_OTC_HIGH_RISK_RECIPIENT}
